### ISSUE TITLE
SC - 1700042032 - número de Solicitudes OK

### ISSUE THREAD

**Issue by danteghirardelli** [danteghirardelli/Pruebas-SC#11]
## Proyecto ReplicaGastos_040517 Código#1700042032
Desde Mayo a Diciembre
![image](https://cloud.githubusercontent.com/assets/21196249/25713501/48b99466-30cb-11e7-8458-8a5cb83877de.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713506/4cbd29e2-30cb-11e7-8b8c-d834877e5ea3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713515/59dddc7a-30cb-11e7-95eb-1f2727cc2371.png)

## Producto Administración
![image](https://cloud.githubusercontent.com/assets/21196249/25713539/6e531c7e-30cb-11e7-98ea-724ffbf9e4e9.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713543/72978978-30cb-11e7-939a-bf7a140d6683.png)

## Asignación Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25713578/90b7113a-30cb-11e7-8ca0-e9442be6148b.png)

## Asignar Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25713603/ab9c47d6-30cb-11e7-97b0-800cc4ff0c0e.png)

## Nueva Asignación de Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25713643/c71499e6-30cb-11e7-9b04-9b8c5b8668a4.png)

## Catalina Jimeno  Secretaria Contable
![image](https://cloud.githubusercontent.com/assets/21196249/25713759/27f550a2-30cc-11e7-8ea6-c5f12cf142e2.png)

## Gasto Personal
![image](https://cloud.githubusercontent.com/assets/21196249/25713777/37aadf3a-30cc-11e7-9d46-aaf26ba5e15b.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25713814/4f948312-30cc-11e7-91d0-baa2b454568c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713821/5722ee7a-30cc-11e7-874b-747398145a2d.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25713912/b1a07066-30cc-11e7-99fc-a0a391823c76.png)

## Horarios
![image](https://cloud.githubusercontent.com/assets/21196249/25713922/c0e364ca-30cc-11e7-8b10-5268a44a67b0.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713964/de271734-30cc-11e7-9683-80c7162db169.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713971/e36837be-30cc-11e7-9803-2b194c21ff13.png)

## Beneficiario #2
![image](https://cloud.githubusercontent.com/assets/21196249/25713990/f7e2a490-30cc-11e7-9c71-75da08ec6f8a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25713998/feff26e0-30cc-11e7-9a09-9f047c466df9.png)

## Gastos Personal
![image](https://cloud.githubusercontent.com/assets/21196249/25714019/0ccd7394-30cd-11e7-97ac-99bf44cc266d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714026/10eea268-30cd-11e7-9196-8e0ac5493425.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25714083/40138338-30cd-11e7-8869-c0c50a0fadc4.png)

## Asignada igual al Beneficiario anterior
![image](https://cloud.githubusercontent.com/assets/21196249/25714097/4f297134-30cd-11e7-9242-b98d4fbccd20.png)

## Beneficiario #3 Administrativo
![image](https://cloud.githubusercontent.com/assets/21196249/25714117/604a887c-30cd-11e7-9df7-ab1be10bda62.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714119/64d01ac4-30cd-11e7-9ffb-906767fd0173.png)

## Gasto Personal
![image](https://cloud.githubusercontent.com/assets/21196249/25714171/815b4204-30cd-11e7-8115-66a186482b3a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714183/89b3c44e-30cd-11e7-909c-87088c6777bf.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25714203/9cca54c6-30cd-11e7-93cc-d1420dcf8341.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714208/a09a1f82-30cd-11e7-923c-23145e8eef6e.png)

## Asignar Beneficiario #4  Contador
![image](https://cloud.githubusercontent.com/assets/21196249/25714232/b10a2d30-30cd-11e7-94ac-f29a0cb0ee1b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714237/b6215172-30cd-11e7-919d-df0256d66bb0.png)

## Gastos en Personal
![image](https://cloud.githubusercontent.com/assets/21196249/25714267/d0c757c4-30cd-11e7-8c11-307de1ef1d63.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714275/d54c4a66-30cd-11e7-91dc-28f7a7e0a65b.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25714299/e446980a-30cd-11e7-8a1f-6ee8836f4475.png)

## Beneficiarios Total (4)
![image](https://cloud.githubusercontent.com/assets/21196249/25714325/fccc9546-30cd-11e7-9a84-2ccf2270204e.png)

## Gastos en Bienes y Servicios
![image](https://cloud.githubusercontent.com/assets/21196249/25714341/0c1cab94-30ce-11e7-95d9-b7a23fe6eb56.png)

## Listado de Gasto de Administración
![image](https://cloud.githubusercontent.com/assets/21196249/25714352/18ffbb94-30ce-11e7-9014-59d0f8e659eb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714362/204d0578-30ce-11e7-92ce-f2b3faa399dd.png)

## Materiales de Oficina
![image](https://cloud.githubusercontent.com/assets/21196249/25714381/30917734-30ce-11e7-977f-2b390af52a79.png)

## Nuevo 
![image](https://cloud.githubusercontent.com/assets/21196249/25714402/400258f0-30ce-11e7-8e11-e97bfd0b68b4.png)

## Gasto  Publicaciones e Impresos
![image](https://cloud.githubusercontent.com/assets/21196249/25714426/57096174-30ce-11e7-91b5-400eaa5fc6eb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25714433/5b461f02-30ce-11e7-9035-ed19a5fd5249.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25714444/68b164da-30ce-11e7-82c0-a8ef2e84ef89.png)

## Gastos Grls Sede Arriendo
![image](https://cloud.githubusercontent.com/assets/21196249/25714620/f5c7515e-30ce-11e7-93fd-2f044905b7e4.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25714624/faa39da4-30ce-11e7-839c-ab36889116e9.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25714646/0d2dc224-30cf-11e7-827d-161166147b70.png)

## Gastos Grls ENEL
![image](https://cloud.githubusercontent.com/assets/21196249/25714663/1daf4ff0-30cf-11e7-822f-b1400f2d9890.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25714672/24b07bee-30cf-11e7-9baa-c6c6944c6b2c.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25714695/34d5d6cc-30cf-11e7-980b-091f9b309eb3.png)

## Gastos Grls WOM
![image](https://cloud.githubusercontent.com/assets/21196249/25718627/273efa62-30dd-11e7-9f99-ca7434289e34.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25718798/cca3fe4e-30dd-11e7-942d-fd1bbc1266d4.png)

## Gastos Grls   Fed Internacional
![image](https://cloud.githubusercontent.com/assets/21196249/25718843/f13cd410-30dd-11e7-82ef-0f81e6cf5c57.png)

## Verificar y Postular
![image](https://cloud.githubusercontent.com/assets/21196249/25718877/026c02ec-30de-11e7-8380-c8986131d51f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25718884/067413ac-30de-11e7-8338-da0f6bf892e8.png)
Mensaje Ingresado.

![image](https://cloud.githubusercontent.com/assets/21196249/25718900/1103c31c-30de-11e7-8cfe-e192e2f6804c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25718909/16eef2f6-30de-11e7-9983-ce28825c88fb.png)

## Evaluar Proyecto Ingresado
![image](https://cloud.githubusercontent.com/assets/21196249/25718970/53cab7d2-30de-11e7-83cb-a5faf812f3f9.png)

## Postular
![image](https://cloud.githubusercontent.com/assets/21196249/25719001/740e5382-30de-11e7-99cc-fb355de39056.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25719002/7486bf8e-30de-11e7-9dc2-c4bbf112884f.png)

## Proyecto Postulado #1700042032
![image](https://cloud.githubusercontent.com/assets/21196249/25719099/b1561158-30de-11e7-9eb5-73ce84cc930b.png)

## Evaluar Proyecto
![image](https://cloud.githubusercontent.com/assets/21196249/25719123/bf88499e-30de-11e7-84dd-85ad55ad4d3c.png)

## Pre seleccionado
![image](https://cloud.githubusercontent.com/assets/21196249/25719160/d5d8af5e-30de-11e7-81ab-47793f9286fd.png)

## Evaluar Proyecto Pre Seleccionado
![image](https://cloud.githubusercontent.com/assets/21196249/25719171/e1684c4e-30de-11e7-91c4-c4242d344e2e.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25719178/e5eba842-30de-11e7-9b87-64ff4a9cb11e.png)
## Seleccionada

![image](https://cloud.githubusercontent.com/assets/21196249/25719186/f01141c4-30de-11e7-8c70-e6454e0e9be7.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25719197/ff2d5ab2-30de-11e7-92c1-51e1b6c417cb.png)
## Aprobada

Proyecto Aprobado # 1700042032

Reporte Antes de SC

 
[Proyecto 1700042032_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/977214/Proyecto.1700042032_AntesSC.pdf)

@felipedonoso 

Ahora realizaré la SC y te aviso para que la apruebes.

**Comment by danteghirardelli** [comment]
## Crear SC #1700042032
![image](https://cloud.githubusercontent.com/assets/21196249/25720248/9b654e5a-30e2-11e7-98f9-6e3d3f624a04.png)

## Generar SC
![image](https://cloud.githubusercontent.com/assets/21196249/25721307/51ff0824-30e6-11e7-8b5f-4d27aea8a650.png)

Monto Proyecto $13.825.000
![image](https://cloud.githubusercontent.com/assets/21196249/25721322/6292e93a-30e6-11e7-8221-6e2cde5b027e.png)

## Nueva Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25721348/7760d106-30e6-11e7-8694-e9fdd4713853.png)

## Editar Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25721414/c2e0ed3c-30e6-11e7-9c51-5f386931a5a9.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25721421/c8eb8624-30e6-11e7-9a14-247b2338a242.png)

@felipedonoso 

## No se puede realizar el cambio porque Cargo es Read Only.

**Comment by danteghirardelli** [comment]
## Se edita Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25750944/c5b29abc-3189-11e7-829e-c09cc36c85ba.png)

## Cambiar por Sandra Zúñiga
![image](https://cloud.githubusercontent.com/assets/21196249/25750961/d8a53dbe-3189-11e7-81c4-188b440ded6d.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25750965/dd2f31b4-3189-11e7-963a-f51ca56f8b4c.png)
Mensaje correcto.

![image](https://cloud.githubusercontent.com/assets/21196249/25750984/e825ca88-3189-11e7-92a1-742a21b8ddd5.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25750986/eca1a640-3189-11e7-88de-8d6434fb2eac.png)

## Se modifica Costo Mensual de $120000 a $112500
![image](https://cloud.githubusercontent.com/assets/21196249/25751019/ff60ba28-3189-11e7-9926-02d8976ff713.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25751029/03fbe206-318a-11e7-9a1d-78a7a6b2c206.png)

## Gasto de Administración
![image](https://cloud.githubusercontent.com/assets/21196249/25751068/2c2e35f8-318a-11e7-8aec-85bb94d70b7b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25751081/33fb7476-318a-11e7-9bc7-83df0be8aede.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25751089/39324b40-318a-11e7-8adc-a4fbb3ef68af.png)

Gastos Generales Fed Internacional Total $2.150.000## 
![image](https://cloud.githubusercontent.com/assets/21196249/25751119/4b44b1a6-318a-11e7-80b0-4027b2e55c78.png)

## Enviar SC
![image](https://cloud.githubusercontent.com/assets/21196249/25751143/5c0cf1ba-318a-11e7-8dd9-896619c887d3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25751147/605eb3c0-318a-11e7-9aca-6c481c79d6b7.png)
Mensaje correcto.

![image](https://cloud.githubusercontent.com/assets/21196249/25751160/6e471f9a-318a-11e7-93d6-79cb593cb592.png)

## Se envió la SC
![image](https://cloud.githubusercontent.com/assets/21196249/25751171/7bf4c5e8-318a-11e7-9764-021631e0a59b.png)

## SC queda en Estado “Aprobado / Solicitud de Cambio / En Revisión”

## Reporte Antes de SC
[Proyecto 1700042032_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/979477/Proyecto.1700042032_AntesSC.pdf)

## Resumen
Debido al reemplazo del personal asignado a las funciones de contabilidad y el incio de sus funciones en el mes de Abril, se solicita aprobar los siguientes cambios:

1.- Reemplazar al beneficiario Sr. Mauricio León RUT 11.153047-5 por la Srta. Sandra Zúñiga,
2.- Los Honorarios de la Srta Zúñiga corresponderán desde los meses de Mayo a Diciembre por $112.500 brutos por mes, total anual de $900.000 
3.- Se solicita traspasar el Monto de $60.000 correspondiente a los Honorarios de la Srta Zúñiga al ítem de Gastos en Bienes y Servicios, Gastos Generales, 
"Pago Gastos de Membresía Anual y Reporte de Títulos, Torneos y Eventos Federación Internacional de Ajedrez (FIDE)" el cual pasa de un monto de $2.090.000 
anual a $2.150.000 anual.

@felipedonoso 
 
Puedes aprobar la SC

**Comment by felipedonoso** [comment]
**Se revisarán las versiones:**
![image](https://cloud.githubusercontent.com/assets/5757157/25811527/f48807e8-33e9-11e7-83f2-4fd9a346e65d.png)

**1.- Reemplazar al beneficiario Sr. Mauricio León RUT 11.153047-5 por la Srta. Sandra Zúñiga,**

![image](https://cloud.githubusercontent.com/assets/5757157/25811791/c39bbf98-33ea-11e7-97f3-c500164cae38.png)

2.- Los Honorarios de la Srta Zúñiga corresponderán desde los meses de Mayo a Diciembre por $112.500 brutos por mes, total anual de $900.000.

![image](https://cloud.githubusercontent.com/assets/5757157/25811843/e453a75a-33ea-11e7-9129-d68ecc854ff0.png)

3.- Se solicita traspasar el Monto de $60.000 correspondiente a los Honorarios de la Srta Zúñiga al ítem de Gastos en Bienes y Servicios, Gastos Generales,
"Pago Gastos de Membresía Anual y Reporte de Títulos, Torneos y Eventos Federación Internacional de Ajedrez (FIDE)" el cual pasa de un monto de $2.090.000
anual a $2.150.000 anual.


**Revisando los gastos en bienes y servicios:**

Se puede apreciar el gasto general de 2.090.000 a **2.150.000**
![image](https://cloud.githubusercontent.com/assets/5757157/25818210/4192311a-3400-11e7-88d7-5a3511323ed4.png)

**_Observación:_**

Se observa que este listado en gastos en Bienes y servicios esta sin información en el proyecto original:
![image](https://cloud.githubusercontent.com/assets/5757157/25818385/d4bed704-3400-11e7-8752-2f73943ba8c4.png)


Se aprobará la SC:

![image](https://cloud.githubusercontent.com/assets/5757157/25818878/71beb316-3402-11e7-9aa3-3ba0d468e5cb.png)

**Comment by felipedonoso** [comment]
Ahora se procederá a crear una nueva solicitud de cambio.

1.- Revisando el estado del proyecto:
![image](https://cloud.githubusercontent.com/assets/5757157/25818972/cd922100-3402-11e7-8500-a2dd229d72d8.png)

2.- Reporte del proyecto: Debe reflejar los cambios antes mencionados.

[Proyecto - 1700042032.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/984475/Proyecto.-.1700042032.pdf)

2.1- Revisando los cambios:

**Gasto en personal:** Contador de Mayo a Diciembre por $112.500 brutos por mes, total anual de $900.000.
![image](https://cloud.githubusercontent.com/assets/5757157/25819274/ddb2999c-3403-11e7-9b59-1abc22a9639d.png)
![image](https://cloud.githubusercontent.com/assets/5757157/25819318/fb1b4bfa-3403-11e7-80ba-a7a2f3f2702c.png)

**Gastos en Bienes y Servicios:** Gasto general de un monto de $2.090.000
anual a $2.150.000 anual.
![image](https://cloud.githubusercontent.com/assets/5757157/25819372/2f3162e4-3404-11e7-8d6a-151df0f37ec5.png)

3.- Revisando las versiones del proyecto: No se visualiza los cambios.

![image](https://cloud.githubusercontent.com/assets/5757157/25819096/377426c2-3403-11e7-9d61-ae488883453f.png)

4.- Creando la SC:
![image](https://cloud.githubusercontent.com/assets/5757157/25819642/fabee03a-3404-11e7-9350-86eb019c1c36.png)

Se modificará el gasto modificado anteriormente, volviendo al proyecto original:

SANDRA ZÚÑIGA =>  MAURICIO LEÓN

![image](https://cloud.githubusercontent.com/assets/5757157/25820407/87ba071a-3407-11e7-8124-ed38cfba47de.png)


Bienes y servicios: Se modificará el gasto en 2.150.000 a 2.090.000:
![image](https://cloud.githubusercontent.com/assets/5757157/25820355/5cde19b4-3407-11e7-8a33-3ec72eb2d65a.png)


Subiendo un Archivo: 

![image](https://cloud.githubusercontent.com/assets/5757157/25821944/5848e14e-340d-11e7-94a9-7250387f93e9.png)

**Comment by felipedonoso** [comment]
Debido a que Pablo elimino la SC, y no cambio los estados de los cambios realizados, se dejará como estaba el proyecto, previo al paso anterior, luego de eso el contador de SC debería ser igual a 2.

![image](https://cloud.githubusercontent.com/assets/5757157/25853299/b9de6a10-34a2-11e7-93be-cbadaea40070.png)


**Subiendo Archivos :** El sistema valido que no supere los 25 MB.
![image](https://cloud.githubusercontent.com/assets/5757157/25853771/441c72c0-34a4-11e7-8cb0-a73bd6d934bd.png)

![image](https://cloud.githubusercontent.com/assets/5757157/25854167/7b963cda-34a5-11e7-9f51-911a4a2e75f3.png)

### Solicitud de cambio enviada:
![image](https://cloud.githubusercontent.com/assets/5757157/25854581/df5adfc2-34a6-11e7-8cd8-2d919c4e0035.png)

**Comment by felipedonoso** [comment]
Revisando la SC:

1.- Archivos Adjuntos: Se pueden observar los 02 archivos que fueron posibles de enviar.
![image](https://cloud.githubusercontent.com/assets/5757157/25855025/6530f720-34a8-11e7-9225-0c7b0c73fc54.png)

2.- Revisar si se repiten los gastos en Bienes y servicios: Esto esta corregido.

![image](https://cloud.githubusercontent.com/assets/5757157/25855090/96955ef0-34a8-11e7-918d-d006c763440a.png)

3.- Revisando la modificación en B y S:

![image](https://cloud.githubusercontent.com/assets/5757157/25855129/aeec3a28-34a8-11e7-9463-531a4cf2c7db.png)

4.- Revisando el gasto en personal:

![image](https://cloud.githubusercontent.com/assets/5757157/25855305/37318898-34a9-11e7-9fea-717c68aa2f39.png)

**Aprobando la SC:**

![image](https://cloud.githubusercontent.com/assets/5757157/25855420/869d3e5e-34a9-11e7-9051-83866fe81ac6.png)

**Revisando las versiones:**

No se observan las 02 versiones:
![image](https://cloud.githubusercontent.com/assets/5757157/25855485/b7297d9e-34a9-11e7-8128-d236ee5efcd6.png)

**Comment by felipedonoso** [comment]
### Creando la 03 SC:

El sistema no permite crear la 03 SC, ya que el límite es 03.

![image](https://cloud.githubusercontent.com/assets/5757157/25856554/b6f10eac-34ac-11e7-9f80-a52f06227f0b.png)


Prueba satisfactoria.

**Pendientes:**

- Versionamiento

**Comment by felipedonoso** [comment]
Se suma una SC al proyecto con esto sería la tercera solicitud para el proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/25902278/81f19d16-356f-11e7-9104-814bd154a12e.png)


**Creando la tercera SC:**

Ya se  puede visualizar el icono de SC:

![image](https://cloud.githubusercontent.com/assets/5757157/25902768/e0606c50-3570-11e7-872c-7223fc6f4531.png)

Nueva SC:
![image](https://cloud.githubusercontent.com/assets/5757157/25902828/09f0ecac-3571-11e7-8e02-b5a3e9990e3d.png)

Solo se modificará el producto:

Antes:

![image](https://cloud.githubusercontent.com/assets/5757157/25902850/1e16bd1a-3571-11e7-9f16-5b1e4e93432d.png)

Después: Me reclama por la comuna. Al presionar guardar no mantiene el dato.**EDITAR**

![image](https://cloud.githubusercontent.com/assets/5757157/25903052/b8270e0a-3571-11e7-829b-1cf2b7457689.png)

![image](https://cloud.githubusercontent.com/assets/5757157/25903108/e1ce21ee-3571-11e7-859d-571faceff4e0.png)

**Se corrige el problema anterior.**

![image](https://cloud.githubusercontent.com/assets/5757157/25908026/827f70ea-357f-11e7-90c1-07f2b37fb54b.png)

Cambio de horario:

![image](https://cloud.githubusercontent.com/assets/5757157/25908079/a5d27038-357f-11e7-806d-e35e27fc4293.png)

Nuevo Horario:

![image](https://cloud.githubusercontent.com/assets/5757157/25908160/d1e6b8dc-357f-11e7-82e8-d876f959f523.png)

SC **Enviada:**

![image](https://cloud.githubusercontent.com/assets/5757157/25915262/5b764402-3597-11e7-8aa0-561f2990808b.png)

**Comment by felipedonoso** [comment]
**Revisando los archivos de la SC:** Total 04 OK.

![image](https://cloud.githubusercontent.com/assets/5757157/25915327/8eb67da0-3597-11e7-9cab-7a8f79aeec1c.png)

**Modificación al producto:**

![image](https://cloud.githubusercontent.com/assets/5757157/25915472/f4c18356-3597-11e7-9a85-bc2b3878c7fc.png)

No se aprecia los cambios en el Horario del Beneficiario.

**Aprobando la SC:**

![image](https://cloud.githubusercontent.com/assets/5757157/25915569/4f3e55c0-3598-11e7-96ac-86c4ff248ae5.png)


Ahora no debería tener opción de poder enviar SC en postulación:

![image](https://cloud.githubusercontent.com/assets/5757157/25915657/892903de-3598-11e7-9827-7ede92e3fa28.png)
