### ISSUE TITLE
Modificar Nombre del proyecto después de una Observación

### ISSUE THREAD

**Issue by felipedonoso** [danteghirardelli/Pruebas-SC#16]
@danteghirardelli, lo que se pretende es que se pueda tomar un proyecto en estado "Incompleto" y se presione verificar postular y quede en estado "Ingresado".

Luego de esto entrar al sitio de Administración, hacer la observación que indique lo siguiente:

"Favor modificar el nombre del proyecto a : "Modificando el nombre del proyecto"

Después al entrar al sitio de postulación editar el nombre del proyecto como se solicita y volver a dejarlo en estado "ingresado". 

![image](https://cloud.githubusercontent.com/assets/5757157/26404562/6702eb9e-4060-11e7-805b-4fe9748de2c0.png)

**Comment by danteghirardelli** [comment]
@felipedonoso 

Problemas con Administración QA
![image](https://cloud.githubusercontent.com/assets/21196249/26406887/a1366e88-4067-11e7-8133-c5ce9c481900.png)

**Comment by danteghirardelli** [comment]
@felipedonoso el problema fue que usé URL equivocada.

**Comment by danteghirardelli** [comment]
## Modificar Nombre del proyecto después de una Observación
Proyecto CambioCargo_050517
![image](https://cloud.githubusercontent.com/assets/21196249/26410599/c94729e4-4071-11e7-8142-1b7215d21ec9.png)
![image](https://cloud.githubusercontent.com/assets/21196249/26410606/cde9cf60-4071-11e7-9457-24019ab3f18d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/26410612/d355f410-4071-11e7-8c43-a14e8fafc6ea.png)

## Se ingresa a la Administración de Proyectos
![image](https://cloud.githubusercontent.com/assets/21196249/26410658/ef244458-4071-11e7-9586-a53f51122963.png)

## En Postulación al Editar Campo “Nombre Proyecto” se muestra solo lectura
![image](https://cloud.githubusercontent.com/assets/21196249/26410692/06b9fa7c-4072-11e7-8512-ce8e9050c92d.png)

@felipedonoso 

Esperaré las modificaciones para realizar otra prueba.

**Comment by felipedonoso** [comment]
Revisando largo de 150 caracteres nombre del proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/26830485/068aef5a-4a97-11e7-9df3-1f529a248870.png)
