### ISSUE TITLE
SC - 1700042022 - ítem de gasto Converges

### ISSUE THREAD

**Issue by danteghirardelli** [danteghirardelli/Pruebas-SC#4]
Realizar SC  Proyecto Código #1700042022
![image](https://cloud.githubusercontent.com/assets/21196249/25403134/b776b9ca-29d1-11e7-9201-bb7557835649.png)

Generar SC
![image](https://cloud.githubusercontent.com/assets/21196249/25403151/c9e79d18-29d1-11e7-8828-a8100a943b6e.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403156/d29804de-29d1-11e7-9aba-3a8a75bc43e8.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403189/f27ab404-29d1-11e7-8dc5-5ce7a74e32e9.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403195/f64b440e-29d1-11e7-8575-e20ef410c018.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403203/fb1d7cb8-29d1-11e7-8067-64b1c244f558.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403209/00e5e8b0-29d2-11e7-9c51-377e9833814e.png)
Se cambia Cargo.
![image](https://cloud.githubusercontent.com/assets/21196249/25403221/0aee0ff4-29d2-11e7-801e-ea9a0489cce1.png)
Mensaje correcto.

![image](https://cloud.githubusercontent.com/assets/21196249/25403227/14678a9c-29d2-11e7-9d4d-d3b380d85282.png)
Ahora aparece con Cargo “ABOGADO”.

Cambio “Gasto Administración"
![image](https://cloud.githubusercontent.com/assets/21196249/25403253/291753c8-29d2-11e7-9664-c1aace61e793.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403263/2ca54928-29d2-11e7-991e-fd30a39f9e66.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403269/30f15a44-29d2-11e7-96b3-6843b5431afe.png)

Tipo Gasto “Viáticos”
![image](https://cloud.githubusercontent.com/assets/21196249/25403296/43cbb8ee-29d2-11e7-8033-a84e2538fe0a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403298/4562864c-29d2-11e7-882d-ad9a4e229dbd.png)
Mensaje correcto.

![image](https://cloud.githubusercontent.com/assets/21196249/25403303/4f68c71e-29d2-11e7-96ad-b993cb346beb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403309/54d4e408-29d2-11e7-814d-f23cc110c8db.png)

Enviar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25403326/642f77ba-29d2-11e7-9242-15e6c681ecac.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403339/6a86f82c-29d2-11e7-908c-5b37f2c7c4b5.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403347/6fb8c4f6-29d2-11e7-86a1-4c1f19852783.png)
Sobrepasa la regla del 5% de límite entre gastos del proyecto: $359999

Reporte
![image](https://cloud.githubusercontent.com/assets/21196249/25403374/82bb4b46-29d2-11e7-9735-e0e5542ace04.png)
Mensaje:
Ha ocurrido un error, intente nuevamente. De continuar el error por favor póngase en contacto con IND.Procedure or function 'SP_CALCULAR_DISTRIBUCION_GASTO_PROYECTO_PRODUCTO_COPIA' expects parameter '@ID_PRODUCTO_COPIA', which was not supplied.
![image](https://cloud.githubusercontent.com/assets/21196249/25403395/8e925676-29d2-11e7-8974-d6ad9cb6195a.png)

Rut aparece incompleto.
![image](https://cloud.githubusercontent.com/assets/21196249/25403410/9928add8-29d2-11e7-9e7c-d57572430a37.png)

Data retrieval failed for the subreport, 'rptProyectoGastosPorMesPorProducto', located at: C:\inetpub\wwwroot\DESARROLLO\IndReportesQA\reportes\rptProyectoGastosPorMesPorProducto.rdlc. Please check the log files.

## Respecto a la Regla del 5%
![image](https://cloud.githubusercontent.com/assets/21196249/25403443/b66e4b50-29d2-11e7-8850-2ec65252d177.png)
Sobrepasa la regla del 5% de límite entre gastos del proyecto: $359999.
Revisar este mensaje debido a que el cálculo según mi opinión no es el correcto.
$26.170.000(Total del Proyecto) por 5% $1.308.500.-

Probar Nuevamente la SC
![image](https://cloud.githubusercontent.com/assets/21196249/25403477/cc4d4890-29d2-11e7-85e4-ee402431e258.png)
Se rechaza la SC para proyecto Código# 1700042022
![image](https://cloud.githubusercontent.com/assets/21196249/25403488/d74798f4-29d2-11e7-9d9b-c4fc29280a13.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403496/dd539d1a-29d2-11e7-999a-b91fab46ebfa.png)

Aunque se evaluó con el éxito el rechazo de la SC para proyecto Código # 1700042022 sigue mostrando Estado: “Aprobado / Solicitud de Cambio / En Revisión”
![image](https://cloud.githubusercontent.com/assets/21196249/25403509/ee2d0f40-29d2-11e7-8642-526566bf6345.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25403515/f314d74a-29d2-11e7-896a-b06d5ff821bc.png)

Se probará SC con Proyecto Código #1700042022
![image](https://cloud.githubusercontent.com/assets/21196249/25403522/fe41a95e-29d2-11e7-813b-79433f282924.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25403524/01e82092-29d3-11e7-9b93-e569b3c90bfd.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403530/06e83de8-29d3-11e7-8354-c0e6a9715f15.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403534/0bec8196-29d3-11e7-90e6-8db1592b8326.png)

Se modifica cargo al Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25403561/16ee9d90-29d3-11e7-8943-1a4dd8660ca0.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403567/1ad68652-29d3-11e7-85ba-b6949dbeba8c.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403573/242ef52c-29d3-11e7-8d37-1dd3a0024fd4.png)

Enviar la Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25403581/2d626e94-29d3-11e7-8dca-05466d47bfcb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403584/32049292-29d3-11e7-97ca-a1bd2d22d7ce.png)
Mensaje correcto.

Elimina Solicitud Incompleta
![image](https://cloud.githubusercontent.com/assets/21196249/25403597/423ced30-29d3-11e7-8351-14dd9d9dc834.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25403600/4610170c-29d3-11e7-9fa9-c883472b233d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403603/4b45bb64-29d3-11e7-95f3-398f15d187d5.png)

Generar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25403619/57314f56-29d3-11e7-886e-0a578f9087d2.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403633/5c36051e-29d3-11e7-96cd-dcb908e647eb.png)

Asignación Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25403644/6673c43a-29d3-11e7-9760-c27bf40fbacb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403646/6aa42de2-29d3-11e7-867c-c7688dfe093e.png)

Se modifica Nombre Beneficiario y Cargo
![image](https://cloud.githubusercontent.com/assets/21196249/25403660/75449494-29d3-11e7-832c-cbc644834102.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25403664/7a74862c-29d3-11e7-88a4-7e726a704495.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403668/7f103172-29d3-11e7-986e-6455f59fbfb2.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25403671/84044c90-29d3-11e7-8673-e468dc630384.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403676/880f7fee-29d3-11e7-8e4d-17e40f4aa72c.png)

Se modifica Tipo de Gasto de Remuneración a Honorario
![image](https://cloud.githubusercontent.com/assets/21196249/25403693/91ecc5da-29d3-11e7-9822-83e9c9dc30f3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403702/95d63d8e-29d3-11e7-9a78-15e5f77dbbdd.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403709/9aaf12a4-29d3-11e7-836d-99816bf002d6.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403711/9f8ffbc6-29d3-11e7-8f84-2ba6f4536f31.png)

Enviar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25403723/ac04cca6-29d3-11e7-85b6-2e08f9002d9b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403729/b0a0c47c-29d3-11e7-91ba-3ed022c1f2a1.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25403734/b55a8eda-29d3-11e7-8535-e8acb901bdbc.png)
Mensaje: “Se ha enviado la solicitud asociada al producto “Deporte Aire Libre”.

![image](https://cloud.githubusercontent.com/assets/21196249/25403746/c1f0e888-29d3-11e7-932c-791e294b97c2.png)

Reporte Antes de la SC
[Proyecto 1700042022_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/956284/Proyecto.1700042022_AntesSC.pdf)

Se realizaron las siguientes modificaciones:
- Edición Beneficiario Cargo.
- Cambio en Tipo de Gasto.
- Verificación de la regla 5% (Sobrepasa la regla del 5 %) --> Gastos del Proyecto $359.999

## - Posteriormente se rechaza la SC.
- Se modifica el Cargo al Beneficiario.
- Se elimina la SC incpmpleta.

## - Nueva SC
- Se modifica Beneficiario y Cargo.
- Se modifica Tipo Gasto..

**Comment by felipedonoso** [comment]
# Proyecto: 1700042022

Se aceptará los cambios, que se debería obtener como resultado:

1. Cambio en Gasto en personal: Dante => Valentina.
2. Cambio en cargo: Abogado => Ingeniero.
3. Converges: ítem 10 al 20

**Revisando el punto 1:**

Lo primero sería cambiar el nombre del icono de "Historial de cambios" a  **_Versiones del proyecto._**
También este icono debe aparecer en todas las instancias sin importar que no exista registros.

![image](https://cloud.githubusercontent.com/assets/5757157/25661061/59210082-2fe5-11e7-97ff-0d175303fdd7.png)

Sería ideal colocar una glosa indicando: **_"La versión 1, corresponde al proyecto Aprobado en un inicio"._**

![image](https://cloud.githubusercontent.com/assets/5757157/25661213/1462e504-2fe6-11e7-8cae-d0382b92f447.png)

Primera versión debe coincidir con el reporte adjuntado por @danteghirardelli.
[Proyecto_201700042022_V.1.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/973316/Proyecto_201700042022_V.1.pdf)

**Con esta imagen se resuelve el punto 1 y 2:**

![image](https://cloud.githubusercontent.com/assets/5757157/25661331/90753d90-2fe6-11e7-899a-5810f6d4322a.png)

**Punto 3 Converges:**

Se debe apreciar una diferencia de $ 7.200.000 del ítem 10 al **20** en **HDA_PROYECTO**:

Imagen antes de aprobar:
![image](https://cloud.githubusercontent.com/assets/5757157/25661433/005836bc-2fe7-11e7-823d-b1555bbb69a1.png)

**Aprobando la SC:**

![image](https://cloud.githubusercontent.com/assets/5757157/25661466/275a69e2-2fe7-11e7-9d34-55e5732be436.png)

**Imagen después de aprobar:**

![image](https://cloud.githubusercontent.com/assets/5757157/25661493/4924a95c-2fe7-11e7-8f9b-a50a7991eee7.png)

**Revisando el reporte:**

Mala lectura en el campo **CARGO**: Debería ser ABOGADO y no CONTADOR AUDITOR:

Original:
![image](https://cloud.githubusercontent.com/assets/5757157/25664022/b7854aac-2fef-11e7-9b05-a6ab289aeede.png)


Error:
![image](https://cloud.githubusercontent.com/assets/5757157/25664006/aac0f244-2fef-11e7-8455-733be7355f6e.png)


Conclusión:

- [x] ConVerges OK
- [ ] Reporte con problemas NOOK
- [ ] Falto revisar el gasto de Alimentación y alojamiento a materiales de oficina.
