### ISSUE TITLE
SC - 1700042017- Correo electrónico, al momento de enviar la SC, no debe decir SC aprobada, sino Enviada.

### ISSUE THREAD

**Issue by danteghirardelli** [danteghirardelli/Pruebas-SC#6]
Proyecto “Preba Solicitud Cambio 1” Código #1700042017
Línea PDE
Producto "Organización de Competencias"

![image](https://cloud.githubusercontent.com/assets/21196249/25482985/6080feaa-2b2a-11e7-8876-d475f7079953.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25482989/64ad3f7a-2b2a-11e7-835f-219e190d0627.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25482996/698bde0c-2b2a-11e7-8439-a6601fbec12e.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483007/6f8cdbee-2b2a-11e7-9841-5bd2d33b0f34.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483012/75e2e4a2-2b2a-11e7-8012-d749a7a3d1f3.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483016/79eb8e14-2b2a-11e7-8e94-96bb293aca53.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483018/7e00d248-2b2a-11e7-8cf0-923765a34723.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483022/8261bba4-2b2a-11e7-91c7-1c3be9bf9a7b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483026/8632ed0c-2b2a-11e7-90fa-8bd80db174c7.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483046/98c60b3e-2b2a-11e7-8549-5045a861e4e1.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483048/9e80f46c-2b2a-11e7-9b4a-f9d96f2bc2ad.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25483051/a26c941e-2b2a-11e7-897d-672571839262.png)

Antes de la SC 
[Proyecto 1700042017_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/961552/Proyecto.1700042017_AntesSC.pdf)

Se realizó el siguiente cambio:
- Modificación "Comuna"

**Comment by felipedonoso** [comment]
1.- Revisando Glosa de la SC:

La glosa corresponde a lo enviado:
`Se modificarán los días y las horas.`

2.- Revisando datos en Converges:

HDA_PROYECTO:

![image](https://cloud.githubusercontent.com/assets/5757157/25488443/6510aa02-2b3d-11e7-9f64-0b1c3320911d.png)

SISTEMA:

![image](https://cloud.githubusercontent.com/assets/5757157/25488470/79183024-2b3d-11e7-8e7f-b4fa6e73e477.png)

HDA_MOVIMIENTO:

![image](https://cloud.githubusercontent.com/assets/5757157/25488754/3c272da4-2b3e-11e7-9628-843b40dc9177.png)

SISTEMA:

![image](https://cloud.githubusercontent.com/assets/5757157/25488778/4fd85760-2b3e-11e7-9561-ace94dc0ed48.png)

CAMBIO REALIZADO EN EL PRODUCTO:

No se aprecia dicho cambio ya que solamente se presenta el mes de inicio y de termino, el cambio realizado solo corresponde a la ubicación. El cambio era de **_SIERRA GORDA => MEJILLONES._**

![image](https://cloud.githubusercontent.com/assets/5757157/25488867/8824a074-2b3e-11e7-9c46-48157825c40e.png)

### Rechazando la SC:

![image](https://cloud.githubusercontent.com/assets/5757157/25488985/e809688a-2b3e-11e7-97f4-7984cc45e855.png)

Se revisará el correo electrónico de la Federación.

![image](https://cloud.githubusercontent.com/assets/5757157/25489058/1e5e9efa-2b3f-11e7-85c2-01e3de6f5c9b.png)

Previo al rechazo también se notifico de la SC enviada:

![image](https://cloud.githubusercontent.com/assets/5757157/25489127/4d51a964-2b3f-11e7-995e-0f9e6f83d001.png)


**ERROR:  Debe decir que la SC ha sido enviada y no Aprobado para evitar confusiones.**


### Revisando el Reporte:

Lo primero es ver el estado del proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/25489254/a006757c-2b3f-11e7-9fdc-3e69fe88658d.png)

![image](https://cloud.githubusercontent.com/assets/5757157/25489311/d034b6b4-2b3f-11e7-86fd-c1ecf2335af7.png)




# Conclusión:

1. Agregar campos restantes del producto, en la parte de Aprobación/Rechazado SC.
2. Correo electrónico, al momento de enviar la SC, no debe decir SC aprobada, sino Enviada.
3. Sugerencia, en lo posible al momento de ir a leer los datos a Converges, y no existe registro colocar sin información. En el caso de Movimientos colocar con rojo "No hay giros" y dejar como esta es una idea.
