### ISSUE TITLE
SC - 1700042997 - Modificación PRODUCTO- Fallida

### ISSUE THREAD

**Issue by danteghirardelli** [danteghirardelli/Pruebas-SC#7]
Proyecto Código #1700042997
Producto "Administración"
![image](https://cloud.githubusercontent.com/assets/21196249/25492384/43e0f434-2b49-11e7-8df1-9e6fe6e7c3bb.png)

Enviar Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25492397/4b1d3ec4-2b49-11e7-8a19-6153de16fb0f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492408/50cc5f44-2b49-11e7-8849-b12244639407.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492413/55a50a5c-2b49-11e7-8e05-002d0ad78afb.png)

## Mensaje correcto porque aún no se ha realizado ningún cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25492429/6713c5e4-2b49-11e7-8314-c6f16cc9333b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492447/6d58c788-2b49-11e7-9245-45027298afb4.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492452/7190a726-2b49-11e7-9ff0-e5714c3fb6b2.png)

## Se elimina Solicitud de Cambio Incompleta
![image](https://cloud.githubusercontent.com/assets/21196249/25492482/84a41898-2b49-11e7-8c6b-6f00d72b97cb.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492486/88cad54c-2b49-11e7-9e3c-03a383fc87ff.png)

Nueva Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25492504/97b117ce-2b49-11e7-8a16-662ccc24ff62.png)

## Generar Nueva Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25492528/ab99e7e8-2b49-11e7-8aed-51ecf7689f4b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492529/afacd71e-2b49-11e7-8113-aaf96866a0b8.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492534/b3e88fb2-2b49-11e7-99c7-5f49989df483.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492542/b9372320-2b49-11e7-9f73-9471996c5087.png)

## Antes de los cambios
![image](https://cloud.githubusercontent.com/assets/21196249/25492577/c99f21ae-2b49-11e7-816a-7ba87b7d3121.png)

## Cambio de Región y Comuna
![image](https://cloud.githubusercontent.com/assets/21196249/25492592/d99f6e4c-2b49-11e7-8b66-af02bc8d3c00.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25492598/dd7afb44-2b49-11e7-9c5a-adbb584977c1.png)

## Cambio Beneficiario y Cargo
![image](https://cloud.githubusercontent.com/assets/21196249/25492611/ebc4be92-2b49-11e7-9bd9-b8fe7ce5a8f3.png)

## Editar 
![image](https://cloud.githubusercontent.com/assets/21196249/25492622/f9afc920-2b49-11e7-95d3-33d3194e9f69.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25492642/0e66dc82-2b4a-11e7-8261-40d2bff5507d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492647/128ffb2c-2b4a-11e7-8baf-7caacdb966d7.png)
Mensaje correcto.

## Cambio Gastos Personales
![image](https://cloud.githubusercontent.com/assets/21196249/25492661/247032a8-2b4a-11e7-98c5-701714c39d76.png)

## Cambio Tipo de Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25492688/369b915c-2b4a-11e7-9841-a07f07811d99.png)

## Desde Honorarios a Remuneración
![image](https://cloud.githubusercontent.com/assets/21196249/25492731/4f2c34f6-2b4a-11e7-979d-91c9824748e0.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25492737/533af32a-2b4a-11e7-849f-79101f1eb7cc.png)

## Productos disponibles para Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25492763/60b47292-2b4a-11e7-840e-7b4a20cca1f0.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492774/65dcad70-2b4a-11e7-84eb-560f8dfa65b7.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25492783/6a94726c-2b4a-11e7-8800-adfcf1980ef5.png)

![image](https://cloud.githubusercontent.com/assets/21196249/25492834/9aecc734-2b4a-11e7-8687-7b3916ac533d.png)

Reporte antes de la SC
[Proyecto 1700042997_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/962181/Proyecto.1700042997_AntesSC.pdf)

## Resumen de Cambios realizados:
-	Modificación de Región y Comuna
-	Cambio Beneficiario y Cargo
-	Cambio Gastos Personales
-	Cambio Tipo de Gasto

**Comment by danteghirardelli** [comment]
@felipedonoso 

Revisando el Proyecto #5 este no me muestra cambios en los Horarios de la Geolocalización.
En Hora Fin aparece con 19:00:00 , es decir nunca hizo la modificación.
Por eso no hay mensaje de Alerta durante la construcción de la SC

[Proyecto1700042021_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/962639/Proyecto1700042021_AntesSC.pdf)

**Comment by danteghirardelli** [comment]
@felipedonoso 

Según lo conversado para que quedemos tranquilo con este tema.
Mañana haré nuevamente esta prueba con un proyecto nuevo. Donde lo importante es ver el tema del cambio de "Hora Fin".

**Comment by felipedonoso** [comment]
**Cambios al producto:**

Región: Metropolitana => **Tarapacá**
Comuna: Santiago => **Huara**

Región: El cambio de región no se aprecia, dice **_Nacional_** para ambos casos:

![image](https://cloud.githubusercontent.com/assets/5757157/25808145/8b8dfc5c-33df-11e7-997c-b9e24b110ee0.png)

**Cambio Beneficiario y Cargo:**

Aldo Garrido => **_Dante Ghirardelli_**
Gerente General => **_Gerente Administrativo Financiero._**

![image](https://cloud.githubusercontent.com/assets/5757157/25808397/50f7ed4a-33e0-11e7-9035-59f596994209.png)

**Cambio Tipo de Gasto:**

De Honorario a **_Remuneración._**

![image](https://cloud.githubusercontent.com/assets/5757157/25808465/8cf58bea-33e0-11e7-8298-9d4e216c1151.png)

**HDA_PROYECTO** antes de la Aprobación:
![image](https://cloud.githubusercontent.com/assets/5757157/25809802/8ad274f0-33e4-11e7-9d7c-9b57fbab0ad9.png)

Aprobando la SC:

Por tiempo de Sesión:

![image](https://cloud.githubusercontent.com/assets/5757157/25809841/ad6636e6-33e4-11e7-8e2a-7e48ed7d79bd.png)

Al presionar Volver redirecciona al login.

![image](https://cloud.githubusercontent.com/assets/5757157/25809909/e1b74430-33e4-11e7-9793-a6b3295a47c2.png)

Se volverá a crear una SC:

![image](https://cloud.githubusercontent.com/assets/5757157/25809979/0c2d4282-33e5-11e7-9409-e5f39820780e.png)

**Revisando las Versiones del proyecto:**

![image](https://cloud.githubusercontent.com/assets/5757157/25810023/2e5ab8ee-33e5-11e7-971d-7afa98687669.png)

La versión 1 
[Proyecto_201700042997_V.14 (1).pdf](https://github.com/danteghirardelli/Pruebas-SC/files/983901/Proyecto_201700042997_V.14.1.pdf)

y el versión 14:
[Proyecto_201700042997_V.1 (1).pdf](https://github.com/danteghirardelli/Pruebas-SC/files/983898/Proyecto_201700042997_V.1.1.pdf)

En HDA_PROYECTO: Solamente el **nombre del proyecto no se visualiza**.

![image](https://cloud.githubusercontent.com/assets/5757157/25818762/2226107e-3402-11e7-8ab7-3d22c805d386.png)

Se cierra el proyecto.
