### ISSUE TITLE
SC - 1700042026- No se puede apreciar las versiones del proyecto - Fallida

### ISSUE THREAD

**Issue by danteghirardelli** [danteghirardelli/Pruebas-SC#8]
## Se crea Proyecto para el Cambio de Horario
Proyecto PruebaHorario_280417   Código#1700042026
![image](https://cloud.githubusercontent.com/assets/21196249/25533991/d4e5768e-2c08-11e7-96bd-8d3f58514a45.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25533996/d901e388-2c08-11e7-8fae-f4d7ecfbd8a7.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534015/e789696c-2c08-11e7-9d2b-bc74130ceb17.png)
Mensaje correcto.

![image](https://cloud.githubusercontent.com/assets/21196249/25534028/f3ad5820-2c08-11e7-83c6-c296cb846ea8.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534031/f8d6886c-2c08-11e7-828b-2706cde420fc.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534034/fcd09e76-2c08-11e7-904d-ea907d6813c7.png)

## Asignación Beneficiario
![image](https://cloud.githubusercontent.com/assets/21196249/25534049/0ee65ed4-2c09-11e7-81f1-d030013e1028.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534058/145d9b3e-2c09-11e7-8362-2adb59d13683.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534071/19100806-2c09-11e7-9ca8-854f3acaee68.png)

## Gasto Personal
![image](https://cloud.githubusercontent.com/assets/21196249/25534096/2a8a7d96-2c09-11e7-9cd4-51338854618e.png)

## Nuevo Gasto
![image](https://cloud.githubusercontent.com/assets/21196249/25534125/3ca08b7e-2c09-11e7-9c0d-14854709297a.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534133/40d6fe26-2c09-11e7-8482-a118d984db6e.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25534154/51f62a24-2c09-11e7-9b97-a463a0c29b5d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534168/57d7e2de-2c09-11e7-891e-8f77e0270f5d.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534171/5923c518-2c09-11e7-9423-197ec229c5f5.png)

## Horarios
![image](https://cloud.githubusercontent.com/assets/21196249/25534192/6e031d44-2c09-11e7-8cee-e013b60eb7b1.png)

Nuevo ## Horario
![image](https://cloud.githubusercontent.com/assets/21196249/25534215/8204d7a6-2c09-11e7-8c83-77c087cf4d4b.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534223/87e03b48-2c09-11e7-8034-516d3780dfd2.png)

## Gastos en Bienes y Servicios
![image](https://cloud.githubusercontent.com/assets/21196249/25534251/97f814b0-2c09-11e7-8004-db24ef079663.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534259/9ba68d58-2c09-11e7-9285-4f49bdb9914b.png)

## Geolocalización
![image](https://cloud.githubusercontent.com/assets/21196249/25534287/b36da73c-2c09-11e7-9c14-db3ae741c4a0.png)

## Verificar y Postular
![image](https://cloud.githubusercontent.com/assets/21196249/25534310/c1af6826-2c09-11e7-852a-a0b93ee37c80.png)

## Proyecto Ingresado
![image](https://cloud.githubusercontent.com/assets/21196249/25534336/d6501708-2c09-11e7-93ba-af76c72515dd.png)

## Postulado
![image](https://cloud.githubusercontent.com/assets/21196249/25534348/e516212e-2c09-11e7-9d50-17578cb77aa6.png)

Proyecto Código ## #170042026
![image](https://cloud.githubusercontent.com/assets/21196249/25534369/f07adb40-2c09-11e7-97a5-5c31cb373cb8.png)

## Aprobada
![image](https://cloud.githubusercontent.com/assets/21196249/25534406/11e9c5c0-2c0a-11e7-8d44-b7da30d3c80f.png)

## Solicitud de Cambio
![image](https://cloud.githubusercontent.com/assets/21196249/25534449/2c0108e2-2c0a-11e7-8ede-412dd63057ef.png)

## Generar SC
![image](https://cloud.githubusercontent.com/assets/21196249/25534487/442fd164-2c0a-11e7-9ee6-74d8b143913f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534496/4c9e6d42-2c0a-11e7-8624-458fe5f3ea90.png)

## Nueva SC
![image](https://cloud.githubusercontent.com/assets/21196249/25534520/60e36cd0-2c0a-11e7-8f51-6f29ba6ff6d5.png)

## Se editará solo Hora Fin
![image](https://cloud.githubusercontent.com/assets/21196249/25534542/75be0930-2c0a-11e7-8feb-268fc0740280.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534551/79c18a16-2c0a-11e7-8cb8-da6ca0cce278.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534554/7ed99c8c-2c0a-11e7-9f91-b54ad32009b8.png)

## Enviar SC
![image](https://cloud.githubusercontent.com/assets/21196249/25534588/9a744ce4-2c0a-11e7-9af4-42246874742f.png)
![image](https://cloud.githubusercontent.com/assets/21196249/25534599/a1128af2-2c0a-11e7-82c9-aa3ed8e92e1f.png)
Mensaje correcto

![image](https://cloud.githubusercontent.com/assets/21196249/25534620/ae7fde4c-2c0a-11e7-9db4-df3c20b66110.png)

Se envió la SC

## Reporte Antes de SC
[Proyecto 1700042026_AntesSC.pdf](https://github.com/danteghirardelli/Pruebas-SC/files/964710/Proyecto.1700042026_AntesSC.pdf)

La finalidad de esta SC es de probar el cambio del "Horario Fin".

**Comment by felipedonoso** [comment]
# 1700042026 - Revisar históricos proyectos.

Se cumple con la Finalidad: _**"La finalidad de esta SC es de probar el cambio del "Horario Fin"."**_

![image](https://cloud.githubusercontent.com/assets/5757157/25636066/9a0b203a-2f56-11e7-959d-b374471ae94f.png)

Se aprobará y veremos el históricos del proyecto:

![image](https://cloud.githubusercontent.com/assets/5757157/25636113/c6a53310-2f56-11e7-9b87-16b699c1b365.png)

### Al revisar el históricos del proyecto:

## **Conclusión:**

No se puede apreciar en el estado **Aprobado.** Esto debería verse en todos los estados.
